title: Domenech 
email: jordi@domenech.tech
description: >- # this means to ignore newlines until "baseurl:"
  Integración de sistemas de control y automatizacion industrial con Siemens,
  programación TIA Portal, PCS7 y Scada Project management industrial
twitter_username: domenech-tech
github_username:  domench-tech
author: domenech.tech
logo: /assets/img/logo.webp
web: https://domenech.tech



# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
domain: domenech-tech.github.io


